const router = require('express').Router();
const auth = require('../middleware/auth');
const { requireRole } = require('../middleware/roles');
const ctrl = require('../controllers/products.controller');
router.get('/categories', auth, ctrl.getCategories);
router.get('/barcode/:barcode', auth, ctrl.getByBarcode);
router.get('/', auth, ctrl.list);
router.get('/:id', auth, ctrl.getById);
router.post('/', auth, requireRole('admin', 'manager'), ctrl.create);
router.put('/:id', auth, requireRole('admin', 'manager'), ctrl.update);
router.delete('/:id', auth, requireRole('admin'), ctrl.deactivate);
module.exports = router;
