const now = new Date();

function daysAgo(n, hour = 10, minute = 0) {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const dummyTransactions = [
  {
    _id: 'txn-001',
    receipt_number: 'REC-20240301-0001',
    customer_name: 'James Mensah',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Wireless Headphones', quantity: 1, unit_price: 89.99, line_total: 89.99 }],
    subtotal: 89.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 89.99,
    amount_paid: 89.99,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1709251200-A1B2C3',
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(1, 9, 15),
  },
  {
    _id: 'txn-002',
    receipt_number: 'REC-20240301-0002',
    customer_name: 'Walk-in',
    cashier_name: 'Admin User',
    items: [
      { product_name: 'USB-C Cable', quantity: 2, unit_price: 12.99, line_total: 25.98 },
      { product_name: 'Phone Case', quantity: 1, unit_price: 19.99, line_total: 19.99 },
    ],
    subtotal: 45.97,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 45.97,
    amount_paid: 50.00,
    change_due: 4.03,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(1, 11, 30),
  },
  {
    _id: 'txn-003',
    receipt_number: 'REC-20240301-0003',
    customer_name: 'Abena Osei',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Laptop Stand', quantity: 1, unit_price: 45.00, line_total: 45.00 }],
    subtotal: 45.00,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 45.00,
    amount_paid: 0,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1709251200-D4E5F6',
    payment_status: 'pending',
    notes: 'Awaiting payment confirmation',
    createdAt: daysAgo(2, 14, 20),
  },
  {
    _id: 'txn-004',
    receipt_number: 'REC-20240228-0001',
    customer_name: 'Kweku Asante',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Mechanical Keyboard', quantity: 1, unit_price: 129.99, line_total: 129.99 }],
    subtotal: 129.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 129.99,
    amount_paid: 129.99,
    change_due: 0,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(3, 10, 5),
  },
  {
    _id: 'txn-005',
    receipt_number: 'REC-20240228-0002',
    customer_name: 'Walk-in',
    cashier_name: 'Admin User',
    items: [
      { product_name: 'Mouse Pad XL', quantity: 1, unit_price: 24.99, line_total: 24.99 },
      { product_name: 'USB Hub', quantity: 1, unit_price: 34.99, line_total: 34.99 },
    ],
    subtotal: 59.98,
    discount_amount: 5.00,
    tax_amount: 0,
    total_amount: 54.98,
    amount_paid: 54.98,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1709164800-G7H8I9',
    payment_status: 'completed',
    notes: 'Applied $5 discount',
    createdAt: daysAgo(3, 15, 45),
  },
  {
    _id: 'txn-006',
    receipt_number: 'REC-20240227-0001',
    customer_name: 'Akosua Boateng',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Bluetooth Speaker', quantity: 1, unit_price: 59.99, line_total: 59.99 }],
    subtotal: 59.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 59.99,
    amount_paid: 59.99,
    change_due: 0,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'refunded',
    notes: 'Customer returned item - defective',
    createdAt: daysAgo(5, 9, 30),
  },
  {
    _id: 'txn-007',
    receipt_number: 'REC-20240227-0002',
    customer_name: 'Kofi Acheampong',
    cashier_name: 'Admin User',
    items: [{ product_name: 'HDMI Cable 2m', quantity: 3, unit_price: 14.99, line_total: 44.97 }],
    subtotal: 44.97,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 44.97,
    amount_paid: 44.97,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1708992000-J1K2L3',
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(5, 13, 10),
  },
  {
    _id: 'txn-008',
    receipt_number: 'REC-20240226-0001',
    customer_name: 'Walk-in',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Power Bank 20000mAh', quantity: 1, unit_price: 49.99, line_total: 49.99 }],
    subtotal: 49.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 49.99,
    amount_paid: 50.00,
    change_due: 0.01,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(6, 10, 55),
  },
  {
    _id: 'txn-009',
    receipt_number: 'REC-20240226-0002',
    customer_name: 'Efua Darko',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Webcam HD', quantity: 1, unit_price: 79.99, line_total: 79.99 }],
    subtotal: 79.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 79.99,
    amount_paid: 79.99,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1708905600-M4N5O6',
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(6, 16, 20),
  },
  {
    _id: 'txn-010',
    receipt_number: 'REC-20240225-0001',
    customer_name: 'Yaw Tetteh',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Smart Watch Band', quantity: 2, unit_price: 22.99, line_total: 45.98 }],
    subtotal: 45.98,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 45.98,
    amount_paid: 45.98,
    change_due: 0,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(8, 11, 0),
  },
  {
    _id: 'txn-011',
    receipt_number: 'REC-20240225-0002',
    customer_name: 'Ama Sarpong',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Desk Lamp LED', quantity: 1, unit_price: 38.00, line_total: 38.00 }],
    subtotal: 38.00,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 38.00,
    amount_paid: 0,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1708732800-P7Q8R9',
    payment_status: 'pending',
    notes: '',
    createdAt: daysAgo(8, 14, 30),
  },
  {
    _id: 'txn-012',
    receipt_number: 'REC-20240224-0001',
    customer_name: 'Walk-in',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Cooling Pad', quantity: 1, unit_price: 29.99, line_total: 29.99 }],
    subtotal: 29.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 29.99,
    amount_paid: 30.00,
    change_due: 0.01,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(10, 9, 45),
  },
  {
    _id: 'txn-013',
    receipt_number: 'REC-20240224-0002',
    customer_name: 'Kwame Nkrumah',
    cashier_name: 'Admin User',
    items: [
      { product_name: 'Wireless Charger', quantity: 1, unit_price: 35.00, line_total: 35.00 },
      { product_name: 'USB-C Cable', quantity: 1, unit_price: 12.99, line_total: 12.99 },
    ],
    subtotal: 47.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 47.99,
    amount_paid: 47.99,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1708560000-S1T2U3',
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(10, 12, 15),
  },
  {
    _id: 'txn-014',
    receipt_number: 'REC-20240223-0001',
    customer_name: 'Adwoa Frimpong',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Gaming Mouse', quantity: 1, unit_price: 69.99, line_total: 69.99 }],
    subtotal: 69.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 69.99,
    amount_paid: 69.99,
    change_due: 0,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(12, 10, 30),
  },
  {
    _id: 'txn-015',
    receipt_number: 'REC-20240223-0002',
    customer_name: 'Nana Adjei',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Microphone USB', quantity: 1, unit_price: 99.99, line_total: 99.99 }],
    subtotal: 99.99,
    discount_amount: 10.00,
    tax_amount: 0,
    total_amount: 89.99,
    amount_paid: 89.99,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1708387200-V4W5X6',
    payment_status: 'completed',
    notes: '10% loyalty discount applied',
    createdAt: daysAgo(12, 15, 0),
  },
  {
    _id: 'txn-016',
    receipt_number: 'REC-20240222-0001',
    customer_name: 'Walk-in',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Cable Organizer', quantity: 4, unit_price: 11.99, line_total: 47.96 }],
    subtotal: 47.96,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 47.96,
    amount_paid: 50.00,
    change_due: 2.04,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(15, 11, 20),
  },
  {
    _id: 'txn-017',
    receipt_number: 'REC-20240222-0002',
    customer_name: 'Gifty Amankwah',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Monitor Stand', quantity: 1, unit_price: 54.99, line_total: 54.99 }],
    subtotal: 54.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 54.99,
    amount_paid: 0,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1708214400-Y7Z8A9',
    payment_status: 'pending',
    notes: '',
    createdAt: daysAgo(15, 16, 45),
  },
  {
    _id: 'txn-018',
    receipt_number: 'REC-20240221-0001',
    customer_name: 'James Mensah',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Earbuds TWS', quantity: 1, unit_price: 44.99, line_total: 44.99 }],
    subtotal: 44.99,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 44.99,
    amount_paid: 44.99,
    change_due: 0,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'refunded',
    notes: 'Refunded - customer changed mind',
    createdAt: daysAgo(18, 9, 0),
  },
  {
    _id: 'txn-019',
    receipt_number: 'REC-20240220-0001',
    customer_name: 'Abena Osei',
    cashier_name: 'Admin User',
    items: [
      { product_name: 'SD Card 64GB', quantity: 2, unit_price: 18.99, line_total: 37.98 },
      { product_name: 'Card Reader', quantity: 1, unit_price: 9.99, line_total: 9.99 },
    ],
    subtotal: 47.97,
    discount_amount: 0,
    tax_amount: 0,
    total_amount: 47.97,
    amount_paid: 47.97,
    change_due: 0,
    payment_method: 'paystack',
    payment_reference: 'PSK-1707955200-B2C3D4',
    payment_status: 'completed',
    notes: '',
    createdAt: daysAgo(20, 13, 30),
  },
  {
    _id: 'txn-020',
    receipt_number: 'REC-20240219-0001',
    customer_name: 'Walk-in',
    cashier_name: 'Admin User',
    items: [{ product_name: 'Wireless Headphones', quantity: 2, unit_price: 89.99, line_total: 179.98 }],
    subtotal: 179.98,
    discount_amount: 20.00,
    tax_amount: 0,
    total_amount: 159.98,
    amount_paid: 159.98,
    change_due: 0,
    payment_method: 'cash',
    payment_reference: null,
    payment_status: 'completed',
    notes: 'Bulk discount applied',
    createdAt: daysAgo(25, 10, 0),
  },
];

export function filterDummyTransactions({ payment_method, status, search, fromDate, toDate } = {}) {
  let data = [...dummyTransactions];
  if (payment_method && payment_method !== 'all') data = data.filter(t => t.payment_method === payment_method);
  if (status && status !== 'all') data = data.filter(t => t.payment_status === status);
  if (search) {
    const q = search.toLowerCase();
    data = data.filter(t =>
      t.receipt_number.toLowerCase().includes(q) ||
      t.customer_name.toLowerCase().includes(q) ||
      t.items.some(i => i.product_name.toLowerCase().includes(q))
    );
  }
  if (fromDate) data = data.filter(t => new Date(t.createdAt) >= new Date(fromDate));
  if (toDate) { const d = new Date(toDate); d.setHours(23, 59, 59, 999); data = data.filter(t => new Date(t.createdAt) <= d); }
  return data;
}

export function getDummySummary() {
  const completed = dummyTransactions.filter(t => t.payment_status === 'completed');
  const total_revenue = completed.reduce((s, t) => s + t.total_amount, 0);
  const paystack_revenue = completed.filter(t => t.payment_method === 'paystack').reduce((s, t) => s + t.total_amount, 0);
  const cash_revenue = completed.filter(t => t.payment_method === 'cash').reduce((s, t) => s + t.total_amount, 0);
  return {
    total_transactions: dummyTransactions.length,
    total_revenue,
    paystack_revenue,
    cash_revenue,
    completed: completed.length,
    pending: dummyTransactions.filter(t => t.payment_status === 'pending').length,
    refunded: dummyTransactions.filter(t => t.payment_status === 'refunded').length,
  };
}
